#!/usr/bin/env bash
# gen-tmux-palette.sh — writes $AID_DIR/tmux/palette.conf from the aid palette.
# See docs/ARCHITECTURE.md for details.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
AID_DIR="${AID_DIR:-$SCRIPT_DIR}"
OUT="$AID_DIR/tmux/palette.conf"
PALETTE="$AID_DIR/nvim/lua/palette.lua"

# ── Load palette into shell variables via Lua ────────────────────────────────
# loadfile() runs palette.lua directly — no require(), no package.path needed.
# The script prints every string key as:  key=value
eval "$(lua - "$PALETTE" <<'LUA'
local f = assert(loadfile(arg[1]))
local p = f()
for k, v in pairs(p) do
  if type(v) == "string" then
    io.write(k .. '=' .. v .. '\n')
  end
end
LUA
)"

# ── Emit palette.conf ────────────────────────────────────────────────────────
mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# tmux/palette.conf — generated by gen-tmux-palette.sh
# DO NOT EDIT — regenerated from nvim/lua/palette.lua at each aid session start.

set -g status-style          "bg=${blue} fg=${fg}"
set -g status-left-length 90
set -g status-right-length 90

set -g status-left  "#[fg=${cursor_fg},bg=${purple},bold] #S #[fg=${purple},bg=${blue},none]  "
set -g status-right "#[fg=${lavender},bg=${blue}] #{pane_current_command} #[fg=${lavender},bg=${blue}]#[fg=${fg},bg=${lavender}] %H:%M #[fg=${purple},bg=${lavender}]#[fg=${cursor_fg},bg=${purple},bold] #{?client_prefix,PREFIX,#h} "

set -g window-status-style          ""
set -g window-status-format         ""
set -g window-status-current-format ""
EOF
