#!/usr/bin/env bash
# gen-tmux-palette.sh — writes $AID_DATA/tmux/palette.conf from the aid palette.
# See docs/ARCHITECTURE.md for details.
# shellcheck disable=SC2154  # palette vars (blue, fg, purple, etc.) are injected via eval of lua output below

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
# AID_DIR — source root (where nvim/lua/palette.lua lives).
# AID_DATA — runtime artifact root (where palette.conf is written).
AID_DIR="${AID_DIR:-$SCRIPT_DIR}"
AID_DATA="${AID_DATA:-$HOME/.local/share/aid}"
OUT="$AID_DATA/tmux/palette.conf"
PALETTE="$AID_DIR/nvim/lua/palette.lua"

# ── Load palette into shell variables via Lua ────────────────────────────────
# loadfile() runs palette.lua directly — no require(), no package.path needed.
# The script prints every string key as:  key=value
eval "$(lua - "$PALETTE" <<'LUA'
local f = assert(loadfile(arg[1]))
local p = f()
for k, v in pairs(p) do
  if type(v) == "string" then
    io.write(k .. '=' .. v .. '\n')
  end
end
LUA
)"

# Powerline glyphs (Nerd Font): right-arrow U+E0B0, left-arrow U+E0B2
PL_R=$(printf '\xee\x82\xb0')   # 
PL_L=$(printf '\xee\x82\xb2')   # 

# ── Emit palette.conf ────────────────────────────────────────────────────────
mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# tmux/palette.conf — generated by gen-tmux-palette.sh
# DO NOT EDIT — regenerated from nvim/lua/palette.lua at each aid session start.

set -g status-style          "bg=${blue} fg=${fg}"
set -g status-left-length 90
set -g status-right-length 90

set -g status-left  "#[fg=${cursor_fg},bg=${purple},bold] #S #[fg=${purple},bg=${blue},none]${PL_R}"
set -g status-right "#[fg=${lavender},bg=${blue}] #{pane_current_command} #[fg=${blue},bg=${lavender}]${PL_L}#[fg=${fg},bg=${lavender}] %H:%M #[fg=${lavender},bg=${purple}]${PL_L}#[fg=${cursor_fg},bg=${purple},bold] #{?client_prefix,PREFIX,#h} "

set -g window-status-style          ""
set -g window-status-format         ""
set -g window-status-current-format ""
EOF
